
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'singapore_parliament_speeches'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'singapore-parliament-speeches'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
docs-paths: ["docs"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

models:
  singapore_parliament_speeches:
    +persist_docs:
      relation: true
      columns: true
    dashboard:
      +materialized: table
      +schema: dashboard_datasets
      +tags: dashboard
    mart:
      +materialized: table
      +schema: mart
      +tags: mart
    mart_prep:
      +materialized: table
      +schema: mart_prep
      +tags: mart_prep
    fact:
      +materialized: table
      +schema: fact
      +tags: fact
    dim:
      +materialized: table
      +schema: dim
      +tags: dim
    stg:
      +materialized: view
      +schema: stg
      +tags: staging
    agg:
      +materialized: table
      +schema: agg
      +tags: aggregates
    dim_prep:
      +materialized: view
      +schema: dim_prep
      +tags: dim_prep

seeds:
  +schema: seeds
