version: 2
sources:
  - name: google_sheets
    description: >
      This source contains data stored in Google Sheets that are manually maintained.
    project: singapore-parliament-speeches
    dataset: google_sheets
    loader: external_table
    tags:
      - source
      - google_sheet
    tables:
      - name: member_of_parliament
        description: >
          Constituency Data that were manually filled.
        external:
          options:
            format: GOOGLE_SHEETS
            uris: ['https://docs.google.com/spreadsheets/d/1Wk_PDlQbWWViTV9NmDPsXwu54TD96ltEycLAKOHe1fA/']
            sheet_range: members_member_of_parliament
            skip_leading_rows: 1
        columns:
          - name: member_name
            data_type: STRING
          - name: constituency
            data_type: STRING
          - name: from_date
            data_type: STRING
          - name: to_date
            data_type: STRING
          - name: accessed_at
            data_type: STRING
      - name: ethnicity
        description: >
          Ethnicity that were manually filled.
        external:
          options:
            format: GOOGLE_SHEETS
            uris: ['https://docs.google.com/spreadsheets/d/1Wk_PDlQbWWViTV9NmDPsXwu54TD96ltEycLAKOHe1fA/']
            sheet_range: members_ethnicity
            skip_leading_rows: 1
        columns:
          - name: member_name
            data_type: STRING
          - name: ethnicity
            data_type: STRING
          - name: is_ethnicity_certain
            data_type: STRING
      - name: year_of_birth
        description: >
          Year of Birth Data that were manually filled.
        external:
          options:
            format: GOOGLE_SHEETS
            uris: ['https://docs.google.com/spreadsheets/d/1Wk_PDlQbWWViTV9NmDPsXwu54TD96ltEycLAKOHe1fA/']
            sheet_range: members_year_of_birth
            skip_leading_rows: 1
        columns:
          - name: member_name
            data_type: STRING
          - name: year_of_birth
            data_type: STRING
          - name: accessed_at
            data_type: STRING
      - name: office_holding
        description: >
          Office Holding (Appointments) Data that were manually filled.
        external:
          options:
            format: GOOGLE_SHEETS
            uris: ['https://docs.google.com/spreadsheets/d/1Wk_PDlQbWWViTV9NmDPsXwu54TD96ltEycLAKOHe1fA/']
            sheet_range: members_office_holding
            skip_leading_rows: 1
        columns:
          - name: member_name
            data_type: STRING
          - name: position
            data_type: STRING
          - name: from_date
            data_type: STRING
          - name: to_date
            data_type: STRING
          - name: accessed_at
            data_type: STRING
      - name: member_name_mapping
        description: >
          Variations of member names which appear in the speeches.
        external:
          options:
            format: GOOGLE_SHEETS
            uris: ['https://docs.google.com/spreadsheets/d/1Wk_PDlQbWWViTV9NmDPsXwu54TD96ltEycLAKOHe1fA/']
            sheet_range: members_mapping
            skip_leading_rows: 1
        columns:
          - name: member_name
            data_type: STRING
          - name: possible_variation
            data_type: STRING
            tests:
              - unique
      - name: member_image_link
        description: >
          Variations of member names which appear in the speeches.
        external:
          options:
            format: GOOGLE_SHEETS
            uris: ['https://docs.google.com/spreadsheets/d/1Wk_PDlQbWWViTV9NmDPsXwu54TD96ltEycLAKOHe1fA/']
            sheet_range: members_image_link
            skip_leading_rows: 1
        columns:
          - name: member_name
            data_type: STRING
            tests:
              - unique
          - name: member_image_link
            data_type: STRING
      - name: party
        description: >
          Which party each member belonged to in which parliament. If parliament is blank, then member was in the same party for all parliaments they were in.
        external:
          options:
            format: GOOGLE_SHEETS
            uris: ['https://docs.google.com/spreadsheets/d/1Wk_PDlQbWWViTV9NmDPsXwu54TD96ltEycLAKOHe1fA/']
            sheet_range: members_party
            skip_leading_rows: 1
        columns:
          - name: member_name
            data_type: STRING
            tests:
              - unique:
                  column_names: [member_name, parliament]
          - name: party
            data_type: STRING
          - name: parliament
            data_type: INTEGER
      - name: member_name_link
        description: >
          URL links to members in the parliament API
        external:
          options:
            format: GOOGLE_SHEETS
            uris: ['https://docs.google.com/spreadsheets/d/1Wk_PDlQbWWViTV9NmDPsXwu54TD96ltEycLAKOHe1fA/']
            sheet_range: members_name_link
            skip_leading_rows: 1
        columns:
          - name: member_name
            data_type: STRING
            tests:
              - unique
          - name: member_link_name
            data_type: STRING
      - name: gender
        description: >
          Gender of each MP.
        external:
          options:
            format: GOOGLE_SHEETS
            uris: ['https://docs.google.com/spreadsheets/d/1Wk_PDlQbWWViTV9NmDPsXwu54TD96ltEycLAKOHe1fA/']
            sheet_range: members_gender
            skip_leading_rows: 1
        columns:
          - name: member_name
            data_type: STRING
            tests:
              - unique
          - name: gender
            data_type: STRING