name: docs
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install Poetry
      run: curl -sSL https://install.python-poetry.org | python3 -

    - name: Add Poetry to PATH
      run: echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Configure Poetry Virtual Environment
      run: poetry config virtualenvs.in-project true

    - name: Install Poetry Dependencies
      run: poetry install --no-interaction --no-ansi

    - name: Create dbt directory
      run: mkdir -p ~/.dbt

    - name: Copy profiles.yml from secrets
      run: echo "$PROFILES_YML" > ~/.dbt/profiles.yml
      shell: bash
      env:
        PROFILES_YML: ${{secrets.DBT_PROFILES_YML}}

    - name: Validate dbt version
      run: poetry run dbt --version

    - name: Validate dbt connection
      run: poetry run dbt debug

    - name: Create target directory
      run: mkdir ./target

    - name: Run dbt dependencies
      run: poetry run dbt deps

    - name: Generate dbt documentation
      run: poetry run dbt docs generate

    - name: Create dbt docs directory
      run: mkdir dbt-docs

    - name: Copy manifest.json to dbt docs
      run: cp target/manifest.json dbt-docs/manifest.json

    - name: Copy catalog.json to dbt docs
      run: cp target/catalog.json dbt-docs/catalog.json

    - name: Copy index.html to dbt docs
      run: cp target/index.html dbt-docs/index.html

    - name: Install ghp-import
      run: pip install ghp-import

    - name: Deploy dbt docs to GitHub Pages
      run: ghp-import -n -p -f dbt-docs/
      env:
        DBT_PROJECT_DIR: ./